from tkinter import *
from tkinter import font
base = Tk()
e = Entry(base, width = 50, borderwidth = 5)
base.title("Simple Calculator")
e.grid(row = 0, column = 0, columnspan = 3, padx = 10, pady = 10)

def button_click(number):
    e.delete(0, END)
    e.get()

helv36 = font.Font(family='Helvetica', size=12)
# def sub()
b0 = Button(base, padx = 42, pady = 15, text = "0", font = helv36, command = Lambda: button_click(0))
b1 = Button(base, padx = 42, pady = 15, text = "1", font = helv36, command = Lambda: button_click(1))
b2 = Button(base, padx = 42, pady = 15, text = "2", font = helv36, command = Lambda: button_click(2))
b3 = Button(base, padx = 42, pady = 15, text = "3", font = helv36, command = Lambda: button_click(3))
b5 = Button(base, padx = 42, pady = 15, text = "5", font = helv36, command = Lambda: button_click(4))
b4 = Button(base, padx = 42, pady = 15, text = "4", font = helv36, command = Lambda: button_click(5))
b6 = Button(base, padx = 42, pady = 15, text = "6", font = helv36, command = Lambda: button_click(6))
b7 = Button(base, padx = 42, pady = 15, text = "7", font = helv36, command = Lambda: button_click(7))
b8 = Button(base, padx = 42, pady = 15, text = "8", font = helv36, command = Lambda: button_click(8))
b9 = Button(base, padx = 42, pady = 15, text = "9", font = helv36, command = Lambda: button_click(9))
plus = Button(base, padx = 42, pady = 15, text = "+", font = helv36, command = Lambda: button_click())
minus = Button(base, padx = 42, pady = 15, text = "-", font = helv36, command = Lambda: button_click())

b0.grid(row = 4, column = 1)
b1.grid(row = 1 , column = 0)
b2.grid(row = 1 , column = 1)
b3.grid(row = 1 , column = 2)
b4.grid(row = 2 , column = 0)
b5.grid(row = 2 , column = 1)
b6.grid(row = 2 , column = 2)
b7.grid(row = 3 , column = 0)
b8.grid(row = 3 , column = 1)
b9.grid(row = 3 , column = 2)
plus.grid(row = 4 , column = 0)
minus.grid(row = 4 , column = 2)
base.mainloop()
